name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Package Windows x64
        run: npm run package-win

      - name: Zip package
        shell: pwsh
        run: Compress-Archive -Path dist\Botw-Save-Editor-win32-x64 -DestinationPath dist\Botw-Save-Editor-${{ github.ref_name }}-win32-x64.zip

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Botw-Savediter ${{ github.ref_name }}
          files: dist/Botw-Save-Editor-${{ github.ref_name }}-win32-x64.zip
          generate_release_notes: false
